import type { WorkbenchIncidentItem, WorkbenchLabels } from "./types";

export const workbenchLabels: WorkbenchLabels = {
  title: "Incident Workbench",
  description: "Server-driven incident operations",
  searchLabel: "Search incidents",
  searchPlaceholder: "Search",
  applyFilters: "Apply",
  clearFilters: "Clear",
  statusFilter: "Status",
  severityFilter: "Severity",
  from: "From",
  to: "To",
  group: "Group",
  density: "Density",
  compact: "Compact",
  comfortable: "Comfortable",
  columns: "Columns",
  pinColumn: "Pin column",
  moveEarlier: "Move earlier",
  moveLater: "Move later",
  narrowColumn: "Narrow",
  widenColumn: "Widen",
  sortColumn: "Sort",
  selectIncident: "Select incident",
  loading: "Loading",
  backgroundRefresh: "Refreshing",
  deniedTitle: "Access denied",
  deniedDescription: "No access",
  errorTitle: "Could not load",
  retry: "Retry",
  emptyTitle: "No incidents",
  emptyDescription: "No incidents yet",
  filteredEmptyTitle: "No matches",
  filteredEmptyDescription: "Change filters",
  loadMore: "Load more",
  loadingMore: "Loading more",
  inspectorTitle: "Incident inspector",
  inspectorDescription: "Authoritative detail",
  inspectorLoading: "Loading incident",
  openRoom: "Open incident room",
  closeInspector: "Close inspector",
  savedViews: "Saved views",
  unsavedView: "Current view",
  saveCurrentView: "Save view",
  updateSavedView: "Update view",
  viewName: "View name",
  privateVisibility: "Private",
  workspaceVisibility: "Workspace",
  conflictTitle: "Saved view changed",
  conflictDescription: "Compare versions",
  conflictDraft: "Your draft",
  conflictCurrent: "Current",
  useCurrent: "Use current",
  retryDraft: "Retry draft",
  selectedCount: "{{count}} selected",
  partialBulk: "{{succeeded}} of {{total}} completed",
  hourShort: "h",
  minuteShort: "m",
  columnsById: {
    key: "Key",
    title: "Title",
    status: "Status",
    severity: "Severity",
    impact: "Impact",
    service: "Primary service",
    affectedServices: "Affected services",
    commander: "Commander",
    responders: "Responders",
    detectedAt: "Detected",
    elapsed: "Elapsed",
    lastUpdateAt: "Last update",
  },
  groupsById: {
    none: "No grouping",
    status: "Status",
    severity: "Severity",
    service: "Service",
    commander: "Commander",
  },
  statusById: {
    detected: "Detected",
    triaging: "Triaging",
    mitigating: "Mitigating",
    monitoring: "Monitoring",
    resolved: "Resolved",
    dismissed: "Dismissed",
  },
  severityById: {
    unknown: "Unknown",
    sev1: "SEV1",
    sev2: "SEV2",
    sev3: "SEV3",
    sev4: "SEV4",
  },
  impactById: {
    unknown: "Unknown",
    none: "None",
    degraded: "Degraded",
    partial_outage: "Partial outage",
    full_outage: "Full outage",
  },
};

export function workbenchItem(index: number): WorkbenchIncidentItem {
  return {
    id: `incident-${index}`,
    key: `INC-${index + 1}`,
    title: `Incident ${index + 1}`,
    summary: null,
    status: "detected",
    severity: index % 2 === 0 ? "sev1" : "sev2",
    impact: "degraded",
    version: 1,
    detectedAt: "2026-08-28T10:00:00.000Z",
    resolvedAt: null,
    lastUpdateAt: "2026-08-28T11:00:00.000Z",
    service: { id: "service-1", name: "Checkout", slug: "checkout" },
    affectedServices: [{ id: "service-1", name: "Checkout", slug: "checkout" }],
    commander: { id: "user-1", name: "Ada" },
    responders: [{ id: "user-2", name: "Grace" }],
  };
}
