import type { TFunction } from "i18next";
import type { WorkbenchLabels } from "./types";

export function getWorkbenchLabels(t: TFunction): WorkbenchLabels {
  const label = (key: string) => t(`relayops:workbench.${key}`);
  return {
    title: label("title"),
    description: label("description"),
    searchLabel: label("searchLabel"),
    searchPlaceholder: label("searchPlaceholder"),
    applyFilters: label("applyFilters"),
    clearFilters: label("clearFilters"),
    statusFilter: label("statusFilter"),
    severityFilter: label("severityFilter"),
    from: label("from"),
    to: label("to"),
    group: label("group"),
    density: label("density"),
    compact: label("compact"),
    comfortable: label("comfortable"),
    columns: label("columns"),
    pinColumn: label("pinColumn"),
    moveEarlier: label("moveEarlier"),
    moveLater: label("moveLater"),
    narrowColumn: label("narrowColumn"),
    widenColumn: label("widenColumn"),
    sortColumn: label("sortColumn"),
    selectIncident: label("selectIncident"),
    loading: label("loading"),
    backgroundRefresh: label("backgroundRefresh"),
    deniedTitle: t("relayops:states.deniedTitle"),
    deniedDescription: t("relayops:states.deniedDescription"),
    errorTitle: t("relayops:states.retryableTitle"),
    retry: t("relayops:states.retry"),
    emptyTitle: label("emptyTitle"),
    emptyDescription: label("emptyDescription"),
    filteredEmptyTitle: label("filteredEmptyTitle"),
    filteredEmptyDescription: label("filteredEmptyDescription"),
    loadMore: label("loadMore"),
    loadingMore: label("loadingMore"),
    inspectorTitle: label("inspectorTitle"),
    inspectorDescription: label("inspectorDescription"),
    inspectorLoading: t("relayops:inspector.loading"),
    openRoom: label("openRoom"),
    closeInspector: label("closeInspector"),
    savedViews: label("savedViews"),
    unsavedView: label("unsavedView"),
    saveCurrentView: label("saveCurrentView"),
    updateSavedView: label("updateSavedView"),
    viewName: label("viewName"),
    privateVisibility: label("privateVisibility"),
    workspaceVisibility: label("workspaceVisibility"),
    conflictTitle: label("conflictTitle"),
    conflictDescription: label("conflictDescription"),
    conflictDraft: label("conflictDraft"),
    conflictCurrent: label("conflictCurrent"),
    useCurrent: label("useCurrent"),
    retryDraft: label("retryDraft"),
    selectedCount: label("selectedCount"),
    partialBulk: label("partialBulk"),
    hourShort: label("hourShort"),
    minuteShort: label("minuteShort"),
    columnsById: {
      key: label("columnsById.key"),
      title: label("columnsById.title"),
      status: label("columnsById.status"),
      severity: label("columnsById.severity"),
      impact: label("columnsById.impact"),
      service: label("columnsById.service"),
      affectedServices: label("columnsById.affectedServices"),
      commander: label("columnsById.commander"),
      responders: label("columnsById.responders"),
      detectedAt: label("columnsById.detectedAt"),
      elapsed: label("columnsById.elapsed"),
      lastUpdateAt: label("columnsById.lastUpdateAt"),
    },
    groupsById: {
      none: label("groupsById.none"),
      status: label("groupsById.status"),
      severity: label("groupsById.severity"),
      service: label("groupsById.service"),
      commander: label("groupsById.commander"),
    },
    statusById: {
      detected: t("relayops:status.detected"),
      triaging: t("relayops:status.triaging"),
      mitigating: t("relayops:status.mitigating"),
      monitoring: t("relayops:status.monitoring"),
      resolved: t("relayops:status.resolved"),
      dismissed: t("relayops:status.dismissed"),
    },
    severityById: {
      unknown: t("relayops:severity.unknown"),
      sev1: label("severityById.sev1"),
      sev2: label("severityById.sev2"),
      sev3: label("severityById.sev3"),
      sev4: label("severityById.sev4"),
    },
    impactById: {
      unknown: t("relayops:impact.unknown"),
      none: t("relayops:impact.none"),
      degraded: t("relayops:impact.degraded"),
      partial_outage: t("relayops:impact.partial_outage"),
      full_outage: t("relayops:impact.full_outage"),
    },
  };
}
